jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Deploy to API
        env:
          API_KEY: ${{ secrets.API_KEY }} 
        run: |
          curl -X POST -H "Authorization: Bearer $API_KEY" https://google.com
